# Generated by Django 4.2.8 on 2023-12-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True)),
                ('model', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=30, null=True)),
                ('color', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engine', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=6, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('gearbox', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=11, null=True)),
                ('passport', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id_deal', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Deal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
                ('post', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=20, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('email', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('man_first', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('man_second', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('man_third', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('woman_first', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('woman_second', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('woman_third', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
    ]
